---
title: "Lung_cancer_analysis"
author: "Xiaocao You"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
df <- read.csv("C:/Users/15827/Desktop/CODES_ME/2023-fall-SUFE-regression-analysis-report/lung-cancer.csv")
head(df)
```
## Data Preprocessing
```{r}
library(dplyr)
# Properties Processing

# filter the uncensored data
uncensored_data <- df[df$Year.of.death.recode != 'Alive at last contact',]
uncensored_data$Year.of.death.recode[uncensored_data$Year.of.death.recode == 'Alive at last contact'] <- 1 # indicator of failure event
uncensored_data$Year.of.death.recode[uncensored_data$Year.of.death.recode != 'Alive at last contact'] <- 0  # indicator of censored

# generate ID of patients
uncensored_data <- uncensored_data %>% select(-Patient.ID)
uncensored_data <- uncensored_data %>%
  mutate(ID = row_number())
uncensored_data %>% dplyr::select("ID", everything())

uncensored_data$Numeric.age <- as.integer(str_extract(uncensored_data$Age.recode.with.single.ages.and.90., "\\d+"))
uncensored_data <- uncensored_data %>% select(-Age.recode.with.single.ages.and.90.)

summary(uncensored_data)
```

## Visualization
```{r}
library(ggplot2)
library(tidyverse)
library(reshape2)
library(RColorBrewer)

# transfer the variables in dataframe into measured variables
uncensored_data$Patient.ID <- as.character(uncensored_data$Patient.ID)
uncensored_data_t <- melt(uncensored_data, id = "Patient.ID")
head(uncensored_data_t)
```


```{r}
summary()
```

```{r}
# Pie Graph
  p_age <- df
  group_by(df$Age.recode.with.single.ages.and.90.)
  summarise(percent = n() / nrow(df))
  ggplot(aes(x = factor(1), y = percent, fill = df$Age.recode.with.single.ages.and.90.)) +
  geom_col(colour = "white")
```